config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'game', to: 'pages#game'
  get 'hiscores', to: 'pages#hiscores'
  get '/invincible', to: 'pages#invincible'
  get '/twoplayers', to: 'pages#twoplayers'
  post '/played', to: 'pages#played'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  #  get username from email
  def username
    # dean@example.com -> ['dean', 'example.com].first -> dean.capitalize -> Dean
    email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: %i[home hiscores invincible twoplayers]
  before_action :set_stats, only: %i[game]
  def home
  end

  def game
  end

  def hiscores
    @users = User.order('win DESC')
  end

  def played
    current_user.win += 1 if params[:win]
    current_user.losses += 1 if params[:loss]
    current_user.ties += 1 if params[:tie]
    current_user.save
  end

  def invincible 
  end

  def twoplayers
  end
  private

  def set_stats
    @wins = current_user.win
    @losses = current_user.losses
    @ties = current_user.ties
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def active(path)
        current_page?(path) ? 'active' : ''
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Tic Tac Toe", root_path, class:'navbar-brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= active(root_path)%>">
        <%= link_to "Home", invincible_path, class:'nav-link' %>
      </li>
    <!-- 
    <li class="nav-item <%= active(game_path)%>">
        <%= link_to "Play Rank AI", game_path, class:'nav-link' %>
      </li>
      <li class="nav-item <%= active(hiscores_path)%>">
        <%= link_to "Hiscores Rank AI", hiscores_path, class:'nav-link' %>
      </li> 
      
      <li class="nav-item <%= active(invincible_path)%>">
       <%= link_to "Invincible AI Game!", invincible_path, class:'nav-link  ' %>
      </li> -->
      <li class="nav-item <%= active(twoplayers_path)%>">
        <%= link_to "Two players", twoplayers_path, class:'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if current_user %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Play A Game", game_path, class:'dropdown-item' %>
            <%= link_to "Account Settings", edit_user_registration_path, class:'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class:'dropdown-item' %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Create An Account", new_user_registration_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class:'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTicTacToeProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/pages/game.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.0.0/p5.min.js"></script>
<div class="container" style="text-align: center">
  <h1 id="scoreText" style="text-align: center">
    <%= pluralize(@wins, "Win") %> | <%= pluralize(@losses, "Loss") %> | <%= pluralize(@ties, "Tie") %>
  </h1>
  <div style="font-size: 32px; padding: 15px;" id="result"></div>
  <button class='custom-btn btn-5' onClick="newGame()" data-title="Replay Tic Tac Toe">Replay Tic Tac Toe</button>
  <div style="font-size: 32px;" id="result2"></div>
</div>
<script>
  var canvas;
  var board;
  var human = 'O';
  var computer = 'X';
  var currentPlayer;
  var available = [];// for location available
  var nodeWidth;
  var nodeHeight;
  var resultText = document.getElementById("result");
  var result2Text = document.getElementById("result2");
  var scoreText = document.getElementById("scoreText");
  var canvasOffset = resultText.getBoundingClientRect().bottom;
  var winner;
  var gameInProgress;
  var score = [
      parseInt("<%= @wins %>"),
      parseInt("<%= @losses %>"),
      parseInt("<%= @ties %>")
  ];
  
  function newGame() {
      noLoop();
      resultText.innerHTML = "No winner yet";
      board = [
          ['', '', ''],
          ['', '', ''],
          ['', '', '']
      ]
      available = board;
      //random start
      currentPlayer = random([human, computer]);
      gameInProgress = true;
      loop();
  }
  
  function setup() {
      //SETUP WIDTH HEIGHT CANVAS TICTACTOE
      // canvas = createCanvas(windowWidth, windowHeight - canvasOffset * 2);
      canvas = createCanvas(400,400);
      nodeWidth = width / 3;
      nodeHeight = height / 3;
      centerCanvas();
      newGame();
  }
  
  function centerCanvas() {
      var canvasX = (windowWidth - width) / 2;
      var canvasY = (windowHeight - height) / 2 + canvasOffset;
      canvas.position(canvasX, canvasY);
  }
  
  function windowResized() {
      resizeCanvas(windowWidth, windowHeight - canvasOffset * 2);
      nodeWidth = width / 3;
      nodeHeight = height / 3;
      centerCanvas();
      drawGrid();
  }
  
  // The ticks of horizontal and vertical lines form the grid table
  function drawGrid() {
      line(nodeWidth, 0, nodeWidth, height);
      line(nodeWidth * 2, 0, nodeWidth * 2, height);
      line(0, nodeHeight, width, nodeHeight);
      line(0, nodeHeight * 2, width, nodeHeight * 2);
  }
  
  function draw() {
      background(220);// background color
      drawGrid();//call gird table
      updateText();
      strokeWeight(5);
  
      for (let i = 0; i < 3; i++) {
          for (let j = 0; j < 3; j++) {
              // if i = 0, x = 0 +
              let x = nodeWidth * i + nodeWidth / 2;
              let y = nodeHeight * j + nodeHeight / 2;
              let spot = board[i][j]
              let xRadius = nodeWidth / 4;
              let yRadius = nodeHeight / 4;
              if (spot == human) {
                  noFill();
                  ellipse(x, y, nodeWidth / 2);
              } else if (spot == computer) {
                  line(x - xRadius, y - yRadius, x + xRadius, y + yRadius);
                  line(x + xRadius, y - yRadius, x - xRadius, y + yRadius)
              }
          }
      }
      if (gameInProgress && checkWinner() && currentPlayer == computer) {
          nextTurn(); // each time a draw is passed, the function is called
      }
  
  }
  
  function updateText() {
      result2Text.innerHTML = currentPlayer + "'s Turn";
  }
  
  function nextTurn() {
      if (currentPlayer == computer) {
          let available = [];
          for (let i = 0; i < 3; i++) {
              for (let j = 0; j < 3; j++) {
                  if (moveAvailable(i, j)) {
                      available.push({
                          i,
                          j
                      })
                  }
              }
          }
          let move = random(available);
          board[move.i][move.j] = computer;
          currentPlayer = human;
      }
  }
  
  function moveAvailable(iPos, jPos) {
      let result;
      if (iPos > 2 || jPos > 2 || iPos < 0 || jPos < 0) {
          result = false;
      } else {
          result = board[iPos][jPos] === '';
      }
      return result;
  }
  
  function mousePressed() {
      if (gameInProgress && checkWinner() && currentPlayer == human) {
          if (mouseX >= 0 && mouseY >= 0 && mouseX <= width && mouseY <= height) {
              let i = floor(mouseX / nodeWidth);
              let j = floor(mouseY / nodeHeight);
              if (moveAvailable(i, j)) {
                  board[i][j] = human;
                  currentPlayer = computer;
              }
          }
      }
  }
  
  function keyReleased() {
      // spacebar = key 32 ->
      if (keyCode === 32 || keyCode === 13 || keyCode === 16 || keyCode === 17 || keyCode === 88 || keyCode === 9 || keyCode === 27 || keyCode === 46) {
          newGame();
      }
  }
  
  // for check win
  function equals3(a, b, c) {
      return a == b && b == c && a != '';
  }
  
  function checkWinner() {
      winner = null;
      let openSpots = 0;
      let result;
  
      // Horizontal Check
      for (let i = 0; i < 3; i++) {
          if (equals3(board[i][0], board[i][1], board[i][2])) {
              winner = board[i][0];
          }
      }
      // Vertical Check
      for (let j = 0; j < 3; j++) {
          if (equals3(board[0][j], board[1][j], board[2][j])) {
              winner = board[0][j];
          }
      }
      // Diagonal Checks
      if (equals3(board[0][0], board[1][1], board[2][2])) {
          winner = board[0][0];
      }
      if (equals3(board[2][0], board[1][1], board[0][2])) {
          winner = board[2][0];
      }
  
      for (let i = 0; i < 3; i++) {
          for (let j = 0; j < 3; j++) {
              if (board[i][j] == '') {
                  openSpots++;
              }
          }
      }
  
      if (winner == null && openSpots == 0) {
          result = 'tie';
      } else {
          result = winner;
      }
  
      if (result !== null) {
          noLoop();
          gameInProgress = false;
          currentPlayer = null;
          if (result == 'tie') {
              resultText.innerHTML = 'Tie!';
          } else {
              resultText.innerHTML = `<span style='color:red;font-weight:bold;'>${result} Win!</span>`;
          }
          setScore(result);
      }
  
      if (result === null) {
          return true;
      } else {
          return false;
      }
  }
  
  function setScore(result) {
      switch (result) {
          case human:
              score[0] += 1;
              break;
          case computer:
              score[1] += 1;
              break;
          default:
              score[2] += 1;
              break;
      }
      setScoreText();
      updateScores(result);
  }
  
  function setScoreText() {
      scoreText.innerHTML = `${score[0]} Wins | ${score[1]} Losses | ${score[2]} Ties`;
  }
  
  function updateScores(result) {
      var formData = new FormData();
      switch (result) {
          case human:
              formData.append("win", 1);
              break;
          case computer:
              formData.append("loss", 1);
              break;
          default:
              formData.append("tie", 1);
              break;
      }
      formData.append("authenticity_token", "<%= form_authenticity_token %>");
      var request = new XMLHttpRequest();
      request.open("POST", "http://localhost:3000/played"); //Change your host link, ex: http://localhost:3000/played
      request.send(formData);
  }
</script>

app/views/pages/hiscores.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 style="text-align:center">
      All Time High Scores
    </h1>
    <% @users.each.with_index do |user, index| %>
      <p>
        <span style='font-weight:bold;'>Rank #<%= index + 1 %>:</span> <span style='font-weight:bold;color:red;'><%= user.username %></span> has won <span style='font-weight:bold;color:blue;'><%= pluralize(user.win, "Game") %></span>
        out of <span style='font-weight:bold;color:blue;'><%= pluralize(user.win + user.losses + user.ties, "Game") %></span> played.
      </p>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container mt-5">
  <div class="jumbotron" style="text-align:center">
    <h1>Tic Tac Toe</h1>
    <!--<%= link_to "Play Rank AI Game!", game_path, class:'custom-btn btn-5' %>
    <br />
    <br />
    <%= link_to "Hiscores Rank AI Game!", hiscores_path, class:'custom-btn btn-5' %>
    <br />
    <hr> -->
    <%= link_to "Two players!", twoplayers_path, class:'custom-btn btn-5' %>
    <br />
    <br />
    <%= link_to "Invincible AI Game!", invincible_path, class:'custom-btn btn-5' %>
    <hr>
    <% if current_user %>
      <%= link_to "Logout", destroy_user_session_path, class:'custom-btn btn-4', method: :delete %>
    <% else %>
      <%= link_to "Create An Account", new_user_registration_path,  class:'custom-btn btn-5' %>
      <br />
      <br />
      <%= link_to "Login", new_user_session_path, class:'custom-btn btn-4' %>
    <% end %>
  </div>
</div>

app/views/pages/invincible.html.erb
<table style='font-family: "Comic Sans MS", cursive, sans-serif;'>
    <tr>
        <td class="cell" id='0'></td>
        <td class="cell" id='1'></td>
        <td class="cell" id='2'></td>
    </tr>
    <tr>
        <td class="cell" id='3'></td>
        <td class="cell" id='4'></td>
        <td class="cell" id='5'></td>
    </tr>
    <tr>
        <td class="cell" id='6'></td>
        <td class="cell" id='7'></td>
        <td class="cell" id='8'></td>
    </tr>
</table>
<div class="endgame">
    <div class="text"></div>
    <button class="btn-2" onClick="startGame()">Replay</button>
</div>
<br><br><br>
<a class="replay" onClick="startGame()" data-title="Replay Tic Tac Toe"></a>
<script>
var origBoard;
const oPlayer = 'O';
const aiPlayer = 'X'
const winCombos = [
    //horizontal
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    //vertical
    [0, 3, 6],
    [1, 4, 7],
    [2, 5, 8],
    //slant
    [0, 4, 8],
    [6, 4, 2]
]

const cells = document.querySelectorAll('.cell');
startGame();

function startGame() {
    document.querySelector(".endgame").style.display = "none";
    origBoard = Array.from(Array(9).keys());
    // console.log(origBoard);
    for (var i = 0; i < cells.length; i++) {
        cells[i].innerText = ''; //clear
        cells[i].style.removeProperty('background-color');
        //add a event process vào click mouse event
        cells[i].addEventListener('click', turnClick, false);
    }
}


function turnClick(square) {
    // // write down the ID of any cell clicked
    // console.log(square.target.id)

    if (typeof origBoard[square.target.id] == 'number') { //If the clicked ID is "number", it means that both human and AI have not played in that position. So.....
        // pass in the ID that clicking 
        turn(square.target.id, oPlayer)

        //After the player takes a turn, check to see if there is a tie
        if (!checkTie()) turn(bestSpot(), aiPlayer);
    }
}

function turn(squareId, objectPlayer) {
    origBoard[squareId] = objectPlayer; //shows the player who has clicked the cell
    document.getElementById(squareId).innerText = objectPlayer; //put more string in the cell with the ID just called

    let gameWon = checkWin(origBoard, objectPlayer) //check win
    if (gameWon) gameOver(gameWon)
}

function checkWin(board, player) {
    let plays = board.reduce((a, e, i) =>
        (e === player) ? a.concat(i) : a, []); /* Use the minify method which will go through every element in the board array. And the concat function will not change the current array, but it will return a new array that will contain the values of the arrays passed in.
    // a is the final value to be returned
    // e is the element in the board array we are running through and indexing*/
    let gameWon = null;
    for (let [index, win] of winCombos.entries())
    /* entries: Returns the enumerable property array of [key, value] pairs with the given object, similar to using the for ... in iteration. */ {
        if (win.every(elem => plays.indexOf(elem) > -1))
        //In essence the every function has the same effect as using a loop to loop through all elements of the array. 
        //The indexOf function will look for an element in the array based on the value of the element, it returns the position (key) of the element if found, and -1 if it is not found.
        {
            //if the player satisfies any array of values in winCombos
            gameWon = { index: index, player: player };
            break;
        }
    }
    return gameWon;
}

//create highlights all cells that make up a victory and prevents the user from entering any more boxes
function gameOver(gameWon) {
    for (let index of winCombos[gameWon.index]) {
        document.getElementById(index).style.backgroundColor =
            gameWon.player == oPlayer ? "blue" : "red";
    }
    for (var i = 0; i < cells.length; i++) {
        cells[i].removeEventListener('click', turnClick, false);
    }

    declareWinner(gameWon.player == oPlayer ? "You win!" : "You lose.");
}

function declareWinner(whoWin) {
    document.querySelector(".endgame").style.display = "block";
    document.querySelector(".endgame .text").innerText = whoWin;
}

function emptySquares() {
    //filter every element from the board array
    return origBoard.filter(s => typeof s == 'number');
}

function bestSpot() {
    // //Find all blank cells and get first element from blank cell. So the AI will always play the first slot
    // return emptySquares()[0];

    return minimax(origBoard, aiPlayer).index;
}

function checkTie() {
    if (emptySquares().length == 0) {
        for (var i = 0; i < cells.length; i++) {
            cells[i].style.backgroundColor = "pink";
            cells[i].removeEventListener('click', turnClick, false);
        }
        declareWinner("Tie Game!")
        return true;
    }
    return false;
}

function minimax(newBoard, player) {
    //  find the indexes of the available spots in the board and set them to a variable called availSpots
    var availSpots = emptySquares();

    // check terminal states
    if (checkWin(newBoard, oPlayer)) {
        return { score: -10 }; // O win
    } else if (checkWin(newBoard, aiPlayer)) {
        return { score: 10 }; // X win
    } else if (availSpots.length === 0) {
        return { score: 0 }; // tie
    }
    // Next, you need to collect the scores from each of the empty spots to evaluate later.
    var moves = [];
    //  Therefore, make an array called moves and loop through empty spots while collecting each move’s index and score in an object called move.
    for (var i = 0; i < availSpots.length; i++) {
        var move = {};
        // Then, set the index number of the empty spot that was stored as a number in the origBoard to the index property of the move object
        move.index = newBoard[availSpots[i]];
        // set the empty spot on the newboard to the current player
        newBoard[availSpots[i]] = player;

        // store the object resulted from the minimax function call that includes a score property to the score property of the move object.
        if (player == aiPlayer) {
            var result = minimax(newBoard, oPlayer);
            move.score = result.score;
        } else {
            var result = minimax(newBoard, aiPlayer);
            move.score = result.score;
        }

        newBoard[availSpots[i]] = move.index;

        // minimax reset new board to what it was before and pushes the move object to the moves aray
        moves.push(move);
    }

    // Then, the minimax algorithm needs to evaluate the best move in the moves array
    var bestMove;
    // It should choose the move with the highest score when AI is playing and the move with the lowest score when the human is playing. So...
    if (player === aiPlayer) {
        // If the player is aiPlayer, it sets a variable called bestScore to a very low number and loops through the moves array, 
        var bestScore = -10000;
        for (var i = 0; i < moves.length; i++) {
            // if a move has a higher score than bestScore, the algorithm stores that move
            if (moves[i].score > bestScore) {
                bestScore = moves[i].score;
                bestMove = i; // In case there are moves with similar score, only the first one will be stored.
            }
        }
    } else {
        var bestScore = 10000;
        for (var i = 0; i < moves.length; i++) {
            if (moves[i].score < bestScore) {
                bestScore = moves[i].score;
                bestMove = i;
            }
        }
    }

    return moves[bestMove];
}

// Replay Tic Tac Toe button
const docStyle = document.documentElement.style
const aElem = document.querySelector('a')
const boundingClientRect = aElem.getBoundingClientRect()

aElem.onmousemove = function (e) {

    const x = e.clientX - boundingClientRect.left
    const y = e.clientY - boundingClientRect.top

    const xc = boundingClientRect.width / 2
    const yc = boundingClientRect.height / 2

    const dx = x - xc
    const dy = y - yc

    docStyle.setProperty('--rx', `${dy / -1}deg`)
    docStyle.setProperty('--ry', `${dx / 10}deg`)
}

aElem.onmouseleave = function (e) {
    docStyle.setProperty('--ty', '0')
    docStyle.setProperty('--rx', '0')
    docStyle.setProperty('--ry', '0')
}

aElem.onmousedown = function (e) {
    docStyle.setProperty('--tz', '-25px')
}

document.body.onmouseup = function (e) {
    docStyle.setProperty('--tz', '-12px')
}
</script>